import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

// POST: Create a new order
export async function POST(req: Request) {
  try {
    const supabase = await createClient();

    // Check active session
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json(
        { message: "Unauthorized. Please log in." },
        { status: 401 },
      );
    }

    const body = await req.json();
    const {
      services,
      weightKg,
      collectionMethod,
      phone,
      instructions,
      pickupTime,
      photosCount,
    } = body;

    const pricePerKg = 50.0;
    const estimatedWeight = weightKg || 3.0;
    const estimatedAmount = estimatedWeight * pricePerKg;

    // Insert order (order_code and pickup_pin are auto-generated by the database trigger)
    const { data: order, error: orderError } = await supabase
      .from("orders")
      .insert({
        user_id: user.id,
        services: services || ["washing"],
        estimated_weight_kg: estimatedWeight,
        price_per_kg: pricePerKg,
        estimated_amount: estimatedAmount,
        collection_method: collectionMethod || "pickup",
        contact_phone: phone || user.phone || "0700000000",
        pickup_instructions: instructions || null,
        pickup_time: pickupTime || "10:00",
        photos_count: photosCount || 0,
        status: "submitted",
      })
      .select()
      .single();

    if (orderError) {
      return NextResponse.json(
        { message: orderError.message },
        { status: 500 },
      );
    }

    return NextResponse.json({
      success: true,
      orderId: order.order_code,
      order,
    });
  } catch (error: any) {
    return NextResponse.json({ message: error.message }, { status: 500 });
  }
}

// GET: Fetch orders for the logged-in user
export async function GET() {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ message: "Unauthorized." }, { status: 401 });
    }

    const { data: orders, error } = await supabase
      .from("orders")
      .select("*")
      .eq("user_id", user.id)
      .order("created_at", { ascending: false });

    if (error) {
      return NextResponse.json({ message: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true, orders });
  } catch (error: any) {
    return NextResponse.json({ message: error.message }, { status: 500 });
  }
}
